In [7]:

import numpy 
import os
from sklearn.model_selection import train_test_split 
from tensorflow.keras.utils import to_categorical as encode
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import LSTM, Dense,SimpleRNN


#### creating paths

In [14]:

address = os.path.join('newdata') 

signs = numpy.array(['salute','ok' ,'love you','come','Namsate','Gracious','You','Me'])

videos,fps,home =30,30,30

In [16]:
enc = {l:n for n, l in enumerate(signs)}

In [17]:
enc


{'salute': 0,
 'ok': 1,
 'love you': 2,
 'come': 3,
 'Namsate': 4,
 'Gracious': 5,
 'You': 6,
 'Me': 7}

In [18]:
seq, numbers = [], []
for action in signs:
    for s in range(videos):
        lst = []
        for x in range(fps):
            r = numpy.load(os.path.join(address, action, str(s), "{}.npy".format(x)))
            lst.append(r)
        seq.append(lst)
        numbers.append(enc[action])

In [19]:
numbers

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7]

In [20]:
X = numpy.array(seq)

In [21]:
X.shape

(240, 30, 1662)

In [22]:
X.shape

(240, 30, 1662)

In [23]:
y = encode(numbers).astype(int)

In [24]:
y

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.09,random_state=0)

In [26]:
y_test.shape

(22, 8)

### LSTM

In [27]:
lstm = Sequential()
lstm.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(30,1662)))
lstm.add(LSTM(128, return_sequences=True, activation='relu'))
lstm.add(LSTM(64, return_sequences=False, activation='relu'))
lstm.add(Dense(64, activation='relu'))
lstm.add(Dense(32, activation='relu'))
lstm.add(Dense(signs.shape[0], activation='softmax'))

In [28]:
X.shape

(240, 30, 1662)

In [29]:
signs.shape[0]

8

In [30]:
lstm.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [42]:
history=lstm.fit(X_train, y_train, epochs=122)

Epoch 1/122
2/2 [==============================] - 4s 111ms/step - loss: 1.2669 - categorical_accuracy: 0.4815
Epoch 2/122
2/2 [==============================] - 0s 68ms/step - loss: 7.6095 - categorical_accuracy: 0.7037
Epoch 3/122
2/2 [==============================] - 0s 69ms/step - loss: 21.3506 - categorical_accuracy: 0.5741
Epoch 4/122
2/2 [==============================] - 0s 68ms/step - loss: 24.7840 - categorical_accuracy: 0.4815
Epoch 5/122
2/2 [==============================] - 0s 70ms/step - loss: 22.4708 - categorical_accuracy: 0.4444
Epoch 6/122
2/2 [==============================] - 0s 64ms/step - loss: 11.9286 - categorical_accuracy: 0.5185
Epoch 7/122
2/2 [==============================] - 0s 71ms/step - loss: 16.4369 - categorical_accuracy: 0.5741
Epoch 8/122
2/2 [==============================] - 0s 72ms/step - loss: 26.5063 - categorical_accuracy: 0.3704
Epoch 9/122
2/2 [==============================] - 0s 64ms/step - loss: 11.3404 - categorical_accuracy: 0.4630
Ep

In [45]:
lstm.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 30, 64)            442112    
                                                                 
 lstm_1 (LSTM)               (None, 30, 128)           98816     
                                                                 
 lstm_2 (LSTM)               (None, 64)                49408     
                                                                 
 dense (Dense)               (None, 64)                4160      
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 596,642
Trainable params: 596,642
Non-trai

In [34]:
y_pred = lstm.predict(X_test)

In [35]:
y_pred[0]

array([3.86611652e-03, 7.09191372e-04, 6.07186637e-04, 9.54079330e-01,
       8.06326699e-03, 5.91022149e-03, 1.26741035e-02, 1.40906312e-02],
      dtype=float32)

In [36]:
signs[numpy.argmax(y_pred[3])]

'love you'

In [32]:
signs[numpy.argmax(y_test[3])]

'love you'

In [52]:
# lstm.save('8signsworkfine.h5')

In [31]:
lstm.load_weights('8signsworkfine.h5')

In [38]:
y_new = lstm.predict(X_test)

In [39]:
ytrue = numpy.argmax(y_test, axis=1).tolist()
y_new = numpy.argmax(y_new, axis=1).tolist()

In [40]:
ytrue

[3, 2, 1, 2, 3, 7, 5, 7, 5, 6, 2, 6, 2, 5, 7, 4, 6, 3, 7, 0, 3, 5]

In [41]:
multilabel_confusion_matrix(ytrue, y_new)

array([[[21,  0],
        [ 0,  1]],

       [[21,  0],
        [ 0,  1]],

       [[18,  0],
        [ 0,  4]],

       [[18,  0],
        [ 0,  4]],

       [[21,  0],
        [ 0,  1]],

       [[18,  0],
        [ 0,  4]],

       [[19,  0],
        [ 0,  3]],

       [[18,  0],
        [ 0,  4]]], dtype=int64)

#### LSTM Accuracy

In [5]:
accuracy_score(ytrue, y_new)

0.84

### RNN model

In [43]:
model_rnn = Sequential()
model_rnn.add(SimpleRNN(64, return_sequences=True, activation='relu', input_shape=(30,1662)))
model_rnn.add(SimpleRNN(128, return_sequences=True, activation='relu'))
model_rnn.add(SimpleRNN(64, return_sequences=False, activation='relu'))
model_rnn.add(Dense(64, activation='relu'))
model_rnn.add(Dense(32, activation='relu'))
model_rnn.add(Dense(signs.shape[0], activation='softmax'))

In [44]:
model_rnn.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [46]:
history_rnn=model_rnn.fit(X_train, y_train, epochs=122)

Epoch 1/122
7/7 [==============================] - 2s 27ms/step - loss: 2.1273 - categorical_accuracy: 0.1284
Epoch 2/122
7/7 [==============================] - 0s 28ms/step - loss: 2.1151 - categorical_accuracy: 0.1009
Epoch 3/122
7/7 [==============================] - 0s 28ms/step - loss: 2.0602 - categorical_accuracy: 0.1743
Epoch 4/122
7/7 [==============================] - 0s 28ms/step - loss: 2.0331 - categorical_accuracy: 0.1789
Epoch 5/122
7/7 [==============================] - 0s 28ms/step - loss: 1.9992 - categorical_accuracy: 0.2018
Epoch 6/122
7/7 [==============================] - 0s 29ms/step - loss: 1.8580 - categorical_accuracy: 0.2982
Epoch 7/122
7/7 [==============================] - 0s 28ms/step - loss: 1.6686 - categorical_accuracy: 0.3028
Epoch 8/122
7/7 [==============================] - 0s 29ms/step - loss: 1.5344 - categorical_accuracy: 0.3853
Epoch 9/122
7/7 [==============================] - 0s 28ms/step - loss: 1.2968 - categorical_accuracy: 0.5229
Epoch 10/1

In [47]:
model_rnn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_3 (SimpleRNN)    (None, 30, 64)            110528    
                                                                 
 simple_rnn_4 (SimpleRNN)    (None, 30, 128)           24704     
                                                                 
 simple_rnn_5 (SimpleRNN)    (None, 64)                12352     
                                                                 
 dense_5 (Dense)             (None, 64)                4160      
                                                                 
 dense_6 (Dense)             (None, 32)                2080      
                                                                 
 dense_7 (Dense)             (None, 8)                 264       
                                                                 
Total params: 154,088
Trainable params: 154,088
Non-tr

In [48]:
result_rnn = model_rnn.predict(X_test) #rnn

In [51]:
yhat_rnn = model_rnn.predict(X_test)
yhat_rnn = numpy.argmax(yhat_rnn, axis=1).tolist()

In [52]:
accuracy_rnn=accuracy_score(ytrue, yhat_rnn)

#### RNN Accuracy

In [53]:
accuracy_rnn

0.5454545454545454

In [74]:
model_rnn.save('final_rnn2.h5')

In [75]:
model_rnn.load_weights('final_rnn2.h5')

In [57]:
signs[numpy.argmax(result_rnn[2])]

'Gracious'

In [58]:
signs[numpy.argmax(y_test[2])]

'ok'